id: AB8123731
title: A Prayer to Guru Rinpoche That Spontaneously Fulfils All Wishes (from the Extremely
  Secret Assembly of Sugatas)
type: translation
pechas:
- I6D6ED3B9
- IF5AA52FA
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:56:10.176373
  last_modified_at: 2023-01-04 11:56:10.176376
  collections:
  - Garwang Chökyi Gyaltsen
  - Works of Tibetan Masters
alignment_to_base:
  I6D6ED3B9/2209: 712B
  IF5AA52FA/4420: 712B
